### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by mehdidanesh98** [koros/AndroidReader#2]
hi koros
first of all thank you for this.
I used your project (androidreader). but when I put a long text in the string, your project loads very slow or maybe crashes.
please check this problem and let me know when this problem is solved.
mehdidanesh98@gmail.com
thank you and best wishes.

**Comment by koros** [comment]
Hi @mehdidanesh98,
Sorry about the issues you are experiencing would you please send me the long text so that i can test it on my End, or rather how long is the text. roughly how many characters so that i can simulate the issue.

**Comment by mehdidanesh98** [comment]
yes, for example:
[https://ufile.io/6203c1](url)

**Comment by mehdidanesh98** [comment]
yes. for example:
[http://s000.tinyupload.com/?file_id=04129783880369468046](url)

**Comment by koros** [comment]
Hi @mehdidanesh98 it seems the url is broken i can't access the link

**Comment by mehdidanesh98** [comment]
sorry for the delay and this the corrected link:
http://s5.picofile.com/file/8287142484/test.txt.html

**Comment by mehdidanesh98** [comment]
hi;
did you check the project?

**Comment by koros** [comment]
Hi Mehdi,

Sorry will have a look at it over weekend since the weekdays leaves me with
very little time, but i am thinking the rendering can begin as soon as the
contents of the first page are available, then a background thread can
continue in the mean time to calculate the bounds for the other pages.
Sorry for late response, will get back to you as soon as possible.

Best regards,
Koros

**Comment by mehdidanesh98** [comment]
hi koros
I think you forgot check the project!
it's true?

**Comment by koros** [comment]
Hi @mehdidanesh98 i have done some enhancements to the pagination logic should be constant time now irrespective of the length of the string, the pagination should also be smoother. Have a look and let me know. Also Remember to upvote the link on stackoverflow so that other pple might find it easily in future.
